### ISSUE TITLE
Falta Apocalipse

### ISSUE THREAD

**Issue by humbertocruz** [thiagobodruk/biblia#10]
Ola, está faltando o livro Apocalipse na versão Json

**Comment by thiagobodruk** [comment]
De quais versões?

**Comment by humbertocruz** [comment]
bom, eu só ví a ACF, nas horas eu não testei.

**Comment by thiagobodruk** [comment]
Acabei de fazer um teste simples e o livro está lá, sim!

`cat pt_acf.json | grep Apocalipse`

Ele vai devolver o livro inteiro.
