### ISSUE TITLE
Meu projeto utilizando a Bíblia em json

### ISSUE THREAD

**Issue by italozaina** [thiagobodruk/biblia#12]
https://github.com/italozaina/projection-html5-icm

Ficou muito bacana, ta de parabéns o Autor ou autores desse projeto maravilhoso da bíblia em json.

Deus abençoe

**Comment by erickamarante** [comment]
Boa tarde.

O projeto ainda está ativo?

Eu me interessei bastante, pois estou procurando um dataset da bíblia para utilizar Machine Learning para evangelizar a partir dos sentimentos das pessoas nas redes sociais, por exemplo: Se uma pessoa está angustiada, triste, etc... o sistema enviará uma mensagem da bíblia para essa pessoa.

**Comment by thiagobodruk** [comment]
Olá! O projeto está ativo, sim. Os arquivos estão disponilizados primariamente em JSON e contemplam as principais versões em português.

**Comment by erickamarante** [comment]
Fantástico!!! 

Utilizarei o seu Dataset, pode ser? Com certeza, farei menção aos dados utilizados e também no que eu puder contribuir, pois preciso relacionar os versículos da bíblia com as promessas de Deus, pois como a ferramenta será baseada em análise de sentimentos, preciso ter esse direcionamento.

Parabéns pela iniciativa.
