### ISSUE TITLE
Coluna: Promessas

### ISSUE THREAD

**Issue by erickamarante** [thiagobodruk/biblia#13]
Boa tarde **Thiago**.

Estou abrindo essa issue para apoiar no mapeamento de promessas da bíblia em seus respectivos versículos.

Abraços.

**Comment by thiagobodruk** [comment]
Como assim?

**Comment by thiagobodruk** [comment]
Não seria mais adequado você fazer um fork do projeto e lá mapear e adaptar o JSON?

**Comment by erickamarante** [comment]
Bom, pensei nisso também e complementar a isso eu li que você faz um scrap da bibliaonline.com.
Nesse caso, acho que eu mapear em meu projeto é o mais adequado.

De qualquer forma obrigado.
