### ISSUE TITLE
Biblia NVT

### ISSUE THREAD

**Issue by amaralma** [thiagobodruk/biblia#14]
Parabéns pelo trabalho!
Além destas traduções, é possível compartilhar a tradução NVT

https://www.biblegateway.com/versions/Nova-Versao-Transformadora-NVT-Bible

https://www.biblegateway.com/versions/Nova-Versao-Transformadora-NVT-Bible#booklist

OBRIGADO!!!!

**Comment by thiagobodruk** [comment]
Meu caro @amaralma! Eu não tenho esta versão na fonte em que pego as traduções. Eu precisaria programar um novo script para extrair a partir deste site. Se você tiver muito interessado nesta versão, me chama em privado para conversarmos.
