### ISSUE TITLE
Mudando um pouco o dump e adicionando novos formatos

### ISSUE THREAD

**Issue by paulohrpinheiro** [thiagobodruk/biblia#15]
Salve Thiago, tudo na paz?

Em primeiro lugar, parabéns pelo repositório. Será muito útil para mim.

Eu tive algumas dificuldades, pois pretendo usar com sqlite3 e outros formatos fáceis de converter sem precisar um banco de dados (CSV por exemplo). Eu tentei usar o JSON mas não consegui (com Python).

Para facilitar minha vida, subi seus dumps em um mysql normal, e depois fiz o dump com `--compatible=ansi` e então converti para _sqlite3_, [com esse conversor bem bacana](https://github.com/dumblob/mysql2sqlite).

E regerei os dumps do MySQL, que com isso são mais fáceis de converter. O próprio `mysqldump` tem uma boa lista de formatos (como Oracle, Postgres e MSSQL, entre outros).

Posso abrir um PR com os novos dumps, adicionando ao menos o sqlite? Posso deixar os comandos que usei num README mais interno, por exemplo. Caso você ache que não seja interessante, peço permissão para fazer um repositório desse jeito que indiquei usando o seu trabalho como base (que, evidentemente, estará com todos os créditos).

Obrigado, abraço, Deus abençoe!

**Comment by thiagobodruk** [comment]
Olá, meu caro! Tudo bem? Te recomendo criar um fork do projeto. Especifica a documentação no teu README.md. Qualquer coisa, dá um grito! :)
