### ISSUE TITLE
Novas versões

### ISSUE THREAD

**Issue by gabriel-seb** [thiagobodruk/biblia#2]
Olá, primeiramente parabéns pelo projeto.

Pesquisando na internet, encontrei algumas outras versões, penso que possam ser úteis a este projeto.

Segue o link para análise:
http://www.sydney.eti.br/?p=175

**Comment by thiagobodruk** [comment]
Olá @gabriel-seb, os arquivos SQL são gerados a partir de um [crawler em Python](https://github.com/thiagobodruk/python/tree/master/biblia) que puxa as informações de qualquer versão do site http://bibliaonline.com.br/. Sendo assim, bastaria executar o crawler nas versões desejadas e corrigir eventuais inconsistências.
