### ISSUE TITLE
Licenças

### ISSUE THREAD

**Issue by arthur-alves** [thiagobodruk/biblia#4]
Olá amigo,

Estas versões da Biblia estão sob algum tipo de licença ou é livre para uso?

**Comment by thiagobodruk** [comment]
Os arquivos em JSON e XML, objeto deste projeto, estão licenciados sob
Creative Commons. As obras originais são de propriedade dos autores e cada
tradução tem uma licença específica, que conforme a utilização, deve ser
verificada com os proprietários dos direitos autorais.

Sem mais, atenciosamente,


*Thiago Bodruk*
+55 (41) 9996-0672



2016-01-28 22:15 GMT-02:00 Arthur Alves <notifications@github.com>:
