### ISSUE TITLE
Problemas no SQL

### ISSUE THREAD

**Issue by cesarak** [thiagobodruk/biblia#5]
Thiago, tem 2 problemas no SQL statement, são eles:
- Não tem no código de inserção o Novo Testamento, todos os inserts são do Antigo Testamento (código 1). A partir do livro 40 (Mateus), ele incluso, o código deve ser o 2;
- Na tabela 'verses', todos os livros estão com um shift de -1. Por exemplo, o livro de Mateus (na tabela de books tem id=40), mas na tabela 'verses',  o livro correspondente o book=39.
  Resolvi esses problemas com um update nas tabelas. ;)
  Abraços

**Comment by gpupo** [comment]
@cesarak que tal fazer um pull request ?

**Comment by thiagobodruk** [comment]
@cesarak qual é o nome do arquivo?

**Comment by cesarak** [comment]
@thiagobodruk o problema foi resolvido executando uma sql para resolver os problemas com os ID's... Vou fazer o upload do arquivo de dump da base com esses problemas resolvidos.

**Comment by thiagobodruk** [comment]
Boa! :D
