### ISSUE TITLE
Ao tentar importar os bancos, diz que a tabela books não existe

### ISSUE THREAD

**Issue by djalmaaraujo** [thiagobodruk/biblia#6]

**Comment by thiagobodruk** [comment]
Qual é o nome do arquivo?

**Comment by djalmaaraujo** [comment]
Qualquer um dos sql

**Comment by thiagobodruk** [comment]
Havia um erro no arquivo SQL. O código estava dando um `DROP TABLE` depois de criar a tabela, ao invés de fazer antes. Corrigi o código das três versões e comitei.

https://github.com/thiagobodruk/biblia/commit/8c33b3e19a7a3ce015d5ad0cc2d256662ee1ecb8?diff=unified
