### ISSUE TITLE
Versão Almeida Revista e Atualizada (ARA)

### ISSUE THREAD

**Issue by jamesmartins** [thiagobodruk/biblia#7]
Muito boa a iniciativa! Mas será que vocês tem como disponibilizar a versão ARA ou vocês teriam o interesse nesta versão em Json/Xml ou Sql?

**Comment by thiagobodruk** [comment]
Olá, @jamesmartins! Infelizmente a base que usamos para extrair os dados não tem esta versão. Fique a vontade para criar e incorporá-la ao projeto.
